### ISSUE TITLE
memory limit

### ISSUE THREAD

**Issue by mickmorseMB** [MaksymBilenko/terraform-provider-aws-synthetics#1]
Hi

Any reason why you are not allowing the memory parameter?

Mick.

**Comment by mickmorseMB** [comment]
MemoryInMB I believe.

**Comment by mickmorseMB** [comment]
I have a fix on a feature if you would like to allow me to push up. 👍

**Comment by MaksymBilenko** [comment]
@mickmorseMB Just missed this parameter. You are welcome to open PR

**Comment by MaksymBilenko** [comment]
@mickmorseMB I've just created new release v0.0.5 with memory_in_mb parameter

**Comment by MaksymBilenko** [comment]
@mickmorseMB Please check and report here

**Comment by mickmorseMB** [comment]
I couldn't push up my branch sorry. Yea looks good - only difference is I've declared memory_in_mb parameter in the canaryCodeOut. 

If you grant me access to push up a branch I'll create a PR.

**Comment by MaksymBilenko** [comment]
@mickmorseMB I think that you should fork this repo to your space, do work there and then create PR from your repo to origin one

**Comment by mickmorseMB** [comment]
yep. just realised that!

https://github.com/MaksymBilenko/terraform-provider-aws-synthetics/pull/2

**Comment by mickmorseMB** [comment]
Was happy to do it 👍 

What about the config code output 

https://github.com/MaksymBilenko/terraform-provider-aws-synthetics/commit/121b6ab988a2bef41b8ad98bb61f0d86fbaab071#diff-ce0b9f2e59198d2fedbec7944dcf4459R504

**Comment by mickmorseMB** [comment]
Thanks!

**Comment by MaksymBilenko** [comment]
Merged and submitted new release v0.1.1
Thank you!

**Comment by mickmorseMB** [comment]
No prob!
