### ISSUE TITLE
Finding the provider plugin

### ISSUE THREAD

**Issue by immo-huneke-zuhlke** [MaksymBilenko/terraform-provider-aws-synthetics#4]
There is apparently a known issue with terraform 0.13. If you augment the `required_providers` block as described in the README here into the top-level Terraform script, it is not correctly picked up by the module that actually invokes the `synthetics_canary` resource. The workaround is to specify `terraform.required_providers.synthetics` in the actual module folder from which it is invoked.

See https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/255 for a similar example.

**Comment by tguvdamm** [comment]
Is this confirmed as being an issue? I have encountered the same and I would expect that you don't need to define a required_providers block containing a provider from a called module in the calling module. I expect to simply define the provider in the calling module and it should pick up that it's for a source in a called module.

It wouldn't make sense that you need redefine providers in the calling module itself.

**Comment by immo-huneke-zuhlke** [comment]
> Is this confirmed as being an issue?

I remember encountering a write-up of the issue somewhere, but I don't know whether it has been formally registered as a Terraform 0.13 issue. I'm trying to get my projects to upgrade to 0.13 so that we can finally move on to 0.14, where it may no longer be an issue.

**Comment by lyd-lyd** [comment]
https://github.com/hashicorp/terraform/issues/25984#issuecomment-680032415

This is correct from 0.13 onwards for 3rd party providers. See above comment.
