### ISSUE TITLE
Terraform 0.12 compatibility

### ISSUE THREAD

**Issue by hamza-tumturk** [MaksymBilenko/terraform-provider-aws-synthetics#8]
Hi,
is this module compatible with tf 0.12?
If so, how would the installation of the plugin look like? Probably worth adding an example in the readme if supported.
Thanks

**Comment by MaksymBilenko** [comment]
Synthetics support was merged https://github.com/hashicorp/terraform-provider-aws/blob/v3.28.0/CHANGELOG.md
Please refer to aws provider
